# Site
repository: lieps/lieps.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name:  lieps
title: Software Engineer
email: liepsof+resume@gmail.com
website: https://lieps.kr

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: liepsof
github_username:  lieps
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
flickr_username: lieps
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: technical blog
  icon: fas fa-globe
  url: https://blog.lieps.kr
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/lieps_cj_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Software Engineer.
  
  <mark>iOS</mark> Developer, Linux/Unix <mark>C</mark> Programmer, <mark>Perl</mark> Mongers.
  
  Interested in <mark>Clojure</mark> and <mark>F</mark>unctional <mark>P</mark>rogramming.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Content Wavve
        link: www.wavve.com
        # link_text: boringcompany.com
        sub_title: iOS Developer
        caption: Febrary 2019 - Present
        quote: >
          -
        description: | # this will include new lines to allow paragraphs
            iOS, iPad, tvOS Developer for Wavve apps.

      - layout: left
        title: CJ Hello
        # link:
        # link_text: boringcompany.com
        sub_title: iOS Developer
        caption: 2012 - 2019 Febrary
        quote: >
          -
        description: | # this will include new lines to allow paragraphs
          CJ Hello (LG HelloVision, currently)
          
          iOS Developer for tving iOS, iPad Apps, CJ Hello Companion App for Cable TV, Viewing iOS App. 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
